/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all assets */
        get: operations["listAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technicians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all technicians */
        get: operations["listTechnicians"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List work orders, optionally filtered by state and priority */
        get: operations["listWorkOrders"];
        put?: never;
        /**
         * Report a new work order
         * @description Creates a work order in state `reported`, unassigned. The server assigns `id`, `reference`, `reportedAt` and `updatedAt`.
         */
        post: operations["createWorkOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work-orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work order id. */
                id: components["parameters"]["WorkOrderId"];
            };
            cookie?: never;
        };
        /** Get a work order by id */
        get: operations["getWorkOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work-orders/{id}/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work order id. */
                id: components["parameters"]["WorkOrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign a technician to a work order
         * @description Replaces any existing assignment. Not allowed once the work order is in a final state.
         */
        post: operations["assignWorkOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work-orders/{id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work order id. */
                id: components["parameters"]["WorkOrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply a lifecycle transition to a work order */
        post: operations["transitionWorkOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate work order counts for the dashboard */
        get: operations["getDashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            ok: boolean;
        };
        /**
         * @description Lifecycle state of a work order. `completed` and `cancelled` are final.
         * @enum {string}
         */
        WorkOrderState: "reported" | "triaged" | "scheduled" | "in_progress" | "completed" | "cancelled";
        /**
         * @description Lifecycle transition. triage: reported→triaged; schedule: triaged→scheduled; start: scheduled→in_progress; complete: in_progress→completed; cancel: triaged|scheduled→cancelled.
         * @enum {string}
         */
        WorkOrderAction: "triage" | "schedule" | "start" | "complete" | "cancel";
        /** @enum {string} */
        Priority: "low" | "medium" | "high" | "critical";
        Asset: {
            id: string;
            /** @description Human-readable asset tag (e.g. a plate or inventory code). */
            tag: string;
            name: string;
            location: string;
        };
        Technician: {
            id: string;
            name: string;
            specialty: string;
        };
        WorkOrder: {
            id: string;
            /** @description Human-readable work order reference, assigned by the server. */
            reference: string;
            assetId: string;
            title: string;
            description: string;
            priority: components["schemas"]["Priority"];
            state: components["schemas"]["WorkOrderState"];
            /** @description Assigned technician, or null while unassigned. Always present. */
            technicianId: string | null;
            /** Format: date-time */
            reportedAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        NewWorkOrder: {
            assetId: string;
            title: string;
            description: string;
            priority: components["schemas"]["Priority"];
        };
        TransitionCommand: {
            action: components["schemas"]["WorkOrderAction"];
        };
        AssignmentCommand: {
            technicianId: string;
        };
        DashboardSummary: {
            /** @description Work orders not in a final state (completed or cancelled). */
            totalOpen: number;
            /** @description Open work orders with priority `critical`. */
            criticalOpen: number;
            /** @description Open work orders with no technician assigned. */
            unassigned: number;
            /** @description Count of work orders per state. Every state is always present. */
            byState: {
                reported: number;
                triaged: number;
                scheduled: number;
                in_progress: number;
                completed: number;
                cancelled: number;
            };
        };
        ApiError: {
            message: string;
            /** @description Optional structured context about the error (e.g. field errors). */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: {
        /** @description Work order id. */
        WorkOrderId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    listAssets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All registered assets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"][];
                };
            };
        };
    };
    listTechnicians: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All registered technicians */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Technician"][];
                };
            };
        };
    };
    listWorkOrders: {
        parameters: {
            query?: {
                /** @description Only return work orders in this state. */
                state?: components["schemas"]["WorkOrderState"];
                /** @description Only return work orders with this priority. */
                priority?: components["schemas"]["Priority"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Work orders matching every supplied filter */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"][];
                };
            };
            /** @description A filter value is not a valid state or priority */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createWorkOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewWorkOrder"];
            };
        };
        responses: {
            /** @description Work order created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"];
                };
            };
            /** @description The payload is invalid or `assetId` does not reference an existing asset */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getWorkOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work order id. */
                id: components["parameters"]["WorkOrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The work order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"];
                };
            };
            /** @description No work order with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    assignWorkOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work order id. */
                id: components["parameters"]["WorkOrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentCommand"];
            };
        };
        responses: {
            /** @description The updated work order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"];
                };
            };
            /** @description No work order with this id, or no technician with `technicianId` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The work order is in a final state (`completed` or `cancelled`) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    transitionWorkOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work order id. */
                id: components["parameters"]["WorkOrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionCommand"];
            };
        };
        responses: {
            /** @description The updated work order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"];
                };
            };
            /** @description The payload is invalid or `action` is not a known action */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No work order with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The action is not allowed from the work order's current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getDashboardSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current dashboard summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
}
